// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <gio/gio.h>

guint glibsharp_glib_dbusannotationinfo_get_ref_count_offset (void);

guint
glibsharp_glib_dbusannotationinfo_get_ref_count_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusAnnotationInfo, ref_count);
}

guint glibsharp_glib_dbusannotationinfo_get_key_offset (void);

guint
glibsharp_glib_dbusannotationinfo_get_key_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusAnnotationInfo, key);
}

guint glibsharp_glib_dbusannotationinfo_get_value_offset (void);

guint
glibsharp_glib_dbusannotationinfo_get_value_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusAnnotationInfo, value);
}

guint glibsharp_glib_dbusannotationinfo_get_annotations_offset (void);

guint
glibsharp_glib_dbusannotationinfo_get_annotations_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusAnnotationInfo, annotations);
}

guint glibsharp_glib_dbusarginfo_get_ref_count_offset (void);

guint
glibsharp_glib_dbusarginfo_get_ref_count_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusArgInfo, ref_count);
}

guint glibsharp_glib_dbusarginfo_get_name_offset (void);

guint
glibsharp_glib_dbusarginfo_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusArgInfo, name);
}

guint glibsharp_glib_dbusarginfo_get_signature_offset (void);

guint
glibsharp_glib_dbusarginfo_get_signature_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusArgInfo, signature);
}

guint glibsharp_glib_dbusarginfo_get_annotations_offset (void);

guint
glibsharp_glib_dbusarginfo_get_annotations_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusArgInfo, annotations);
}

guint glibsharp_glib_dbusinterfaceinfo_get_ref_count_offset (void);

guint
glibsharp_glib_dbusinterfaceinfo_get_ref_count_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusInterfaceInfo, ref_count);
}

guint glibsharp_glib_dbusinterfaceinfo_get_name_offset (void);

guint
glibsharp_glib_dbusinterfaceinfo_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusInterfaceInfo, name);
}

guint glibsharp_glib_dbusinterfaceinfo_get_methods_offset (void);

guint
glibsharp_glib_dbusinterfaceinfo_get_methods_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusInterfaceInfo, methods);
}

guint glibsharp_glib_dbusinterfaceinfo_get_signals_offset (void);

guint
glibsharp_glib_dbusinterfaceinfo_get_signals_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusInterfaceInfo, signals);
}

guint glibsharp_glib_dbusinterfaceinfo_get_properties_offset (void);

guint
glibsharp_glib_dbusinterfaceinfo_get_properties_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusInterfaceInfo, properties);
}

guint glibsharp_glib_dbusinterfaceinfo_get_annotations_offset (void);

guint
glibsharp_glib_dbusinterfaceinfo_get_annotations_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusInterfaceInfo, annotations);
}

guint glibsharp_glib_dbusmethodinfo_get_ref_count_offset (void);

guint
glibsharp_glib_dbusmethodinfo_get_ref_count_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusMethodInfo, ref_count);
}

guint glibsharp_glib_dbusmethodinfo_get_name_offset (void);

guint
glibsharp_glib_dbusmethodinfo_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusMethodInfo, name);
}

guint glibsharp_glib_dbusmethodinfo_get_in_args_offset (void);

guint
glibsharp_glib_dbusmethodinfo_get_in_args_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusMethodInfo, in_args);
}

guint glibsharp_glib_dbusmethodinfo_get_out_args_offset (void);

guint
glibsharp_glib_dbusmethodinfo_get_out_args_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusMethodInfo, out_args);
}

guint glibsharp_glib_dbusmethodinfo_get_annotations_offset (void);

guint
glibsharp_glib_dbusmethodinfo_get_annotations_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusMethodInfo, annotations);
}

guint glibsharp_glib_dbusnodeinfo_get_ref_count_offset (void);

guint
glibsharp_glib_dbusnodeinfo_get_ref_count_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusNodeInfo, ref_count);
}

guint glibsharp_glib_dbusnodeinfo_get_path_offset (void);

guint
glibsharp_glib_dbusnodeinfo_get_path_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusNodeInfo, path);
}

guint glibsharp_glib_dbusnodeinfo_get_interfaces_offset (void);

guint
glibsharp_glib_dbusnodeinfo_get_interfaces_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusNodeInfo, interfaces);
}

guint glibsharp_glib_dbusnodeinfo_get_nodes_offset (void);

guint
glibsharp_glib_dbusnodeinfo_get_nodes_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusNodeInfo, nodes);
}

guint glibsharp_glib_dbusnodeinfo_get_annotations_offset (void);

guint
glibsharp_glib_dbusnodeinfo_get_annotations_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusNodeInfo, annotations);
}

guint glibsharp_glib_dbuspropertyinfo_get_ref_count_offset (void);

guint
glibsharp_glib_dbuspropertyinfo_get_ref_count_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusPropertyInfo, ref_count);
}

guint glibsharp_glib_dbuspropertyinfo_get_name_offset (void);

guint
glibsharp_glib_dbuspropertyinfo_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusPropertyInfo, name);
}

guint glibsharp_glib_dbuspropertyinfo_get_signature_offset (void);

guint
glibsharp_glib_dbuspropertyinfo_get_signature_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusPropertyInfo, signature);
}

guint glibsharp_glib_dbuspropertyinfo_get_flags_offset (void);

guint
glibsharp_glib_dbuspropertyinfo_get_flags_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusPropertyInfo, flags);
}

guint glibsharp_glib_dbuspropertyinfo_get_annotations_offset (void);

guint
glibsharp_glib_dbuspropertyinfo_get_annotations_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusPropertyInfo, annotations);
}

guint glibsharp_glib_dbussignalinfo_get_ref_count_offset (void);

guint
glibsharp_glib_dbussignalinfo_get_ref_count_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusSignalInfo, ref_count);
}

guint glibsharp_glib_dbussignalinfo_get_name_offset (void);

guint
glibsharp_glib_dbussignalinfo_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusSignalInfo, name);
}

guint glibsharp_glib_dbussignalinfo_get_args_offset (void);

guint
glibsharp_glib_dbussignalinfo_get_args_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusSignalInfo, args);
}

guint glibsharp_glib_dbussignalinfo_get_annotations_offset (void);

guint
glibsharp_glib_dbussignalinfo_get_annotations_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GDBusSignalInfo, annotations);
}

